### ISSUE TITLE
GIACT already knows about JSON

### ISSUE THREAD

**Issue by alexherbo2** [marksgarcia/giact-api-call#1]
Hey,

Just so you know, GIACT has an API for JSON.

https://sandbox.api.giact.com/verificationservices/web_api/Help/Api/POST-web_api-inquiries_v5_8

**Comment by marksgarcia** [comment]
Thank you for this. I knew that they had one, but the links I had been provided for it were deprecated and I didn't have a link in my dev console. As such, I was working with what I thought to be my only way of implementing this at the time. I'll be updating this to utilize the POST web api. Cheers!

**Comment by marksgarcia** [comment]
@alexherbo2 thank you again. This issue has been resolved in the most recent push.
